export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'


export const USER_COMPLETE_PROFILE_REQUEST = 'USER_COMPLETE_PROFILE_REQUEST'
export const USER_COMPLETE_PROFILE_SUCCESS = 'USER_COMPLETE_PROFILE_SUCCESS'
export const USER_COMPLETE_PROFILE_FAILED = 'USER_COMPLETE_PROFILE_FAILED'
