export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE'

export const TEAM_REGISTER_REQUEST = 'TEAM_REGISTER_REQUEST'
export const TEAM_REGISTER_SUCCESS = 'TEAM_REGISTER_SUCCESS'
export const TEAM_REGISTER_FAILURE = 'TEAM_REGISTER_FAILURE'
