export const EVENT_CATEGORIES_REQUEST = 'EVENT_CATEGORIES_REQUEST'
export const EVENT_CATEGORIES_SUCCESS = 'EVENT_CATEGORIES_SUCCESS'
export const EVENT_CATEGORIES_FAILURE = 'EVENT_CATEGORIES_FAILURE'
