export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE'

export const EVENT_LIST_SEARCH_REQUEST = 'EVENT_LIST_SEARCH_REQUEST'
export const EVENT_LIST_SEARCH_SUCCESS = 'EVENT_LIST_SEARCH_SUCCESS'
export const EVENT_LIST_SEARCH_FAILURE = 'EVENT_LIST_SEARCH_FAILURE'
